# Generated by Django 5.0.6 on 2024-05-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cppquestion',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='pythonquestion',
            name='quiz',
        ),
        migrations.AddField(
            model_name='cppquiz',
            name='questions',
            field=models.ManyToManyField(related_name='quizzes', to='quizzes.cppquestion'),
        ),
        migrations.AddField(
            model_name='pythonquiz',
            name='questions',
            field=models.ManyToManyField(related_name='quizzes', to='quizzes.pythonquestion'),
        ),
    ]
