# Generated by Django 5.0.6 on 2024-05-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_remove_cppquestion_quiz_remove_pythonquestion_quiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cppquestion',
            name='text',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pythonquestion',
            name='text',
            field=models.TextField(max_length=255),
        ),
    ]
