# Generated by Django 5.0.6 on 2024-05-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_cppquestion_text_alter_pythonquestion_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cppresult',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pythonresult',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
