# Generated by Django 5.0.6 on 2024-05-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_cppresult_attempts_pythonresult_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cppresult',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pythonresult',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
