# Generated by Django 5.0.6 on 2024-05-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonCPP',
            fields=[
                ('lesson', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('banner', models.ImageField(blank=True, default='cpp.png', upload_to='')),
                ('is_finished', models.BooleanField(default=False)),
                ('slug', models.SlugField(default='')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
