# Generated by Django 5.0.6 on 2024-05-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPY',
            fields=[
                ('lesson', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('banner', models.ImageField(blank=True, default='py.png', upload_to='')),
                ('is_finished', models.BooleanField(default=False)),
                ('slug', models.SlugField(default='')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
