# Generated by Django 5.0.6 on 2024-05-14 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_lessonpy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncpp',
            name='previous_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.lessoncpp'),
        ),
        migrations.AddField(
            model_name='lessonpy',
            name='previous_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.lessonpy'),
        ),
        migrations.CreateModel(
            name='LessonCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('lesson_cpp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.lessoncpp')),
                ('lesson_py', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.lessonpy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
