# Generated by Django 5.0.6 on 2024-05-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_lessoncpp_previous_lesson_lessonpy_previous_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncompletion',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
